bn_wm = false
m_gear = true
l_mc = true
nosleep = false
dc_nervous = false
dashforward = true
hardattrb = true
psive_fb = true
sk_caskill = true
sk_gattshot = true
sk_smai = true
sk_noburn = false
pl_smai = true
zb_dbs = true
zb_pblock = false
zb_bblock = false
zb_allbreaker = true
zb_newabi = false
zb_ttnt = false
zb_noburn = true
zb_smoften = false
cr_smai = true
cr_ssnow = true
cr_sap = false
cr_disguide = true
sp_shtweb = true
sp_invis = true
em_curse = true
em_invis = true
em_caskill = true
ws_caskill = true
dr_caskill = true
dr_curse = true
mw_enable = true
mw_burning = true
mw_freeze = true
mw_leviation = true
mw_spread = true
mw_drop = true
jk_rsum = true
bl_caskill = true
bl_spl = true
bl_spawnao = false
bl_usecurse = true
wm_rsum = true
slime_sb = true
sfish_ife = true
vd_statue = true
ws_tc = true
ptom_sleep = false
ptom_carry = false
ptom_rsum = false
ptom_invis = true
gh_smul = true
ilu_rsum = false
